name: build

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: cargo build --release --locked

  pack:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Make artifact directory
        run: mkdir -p ./artifacts/${{ github.repository }}

      - name: ls workspace
        run: ls -alR ${{ github.workspace }}

      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./artifacts/${{ github.repository }}/app.zip ${{ github.workspace}}/codedeploy ${{ github.workspace }}/appspec.yml ${{ github.workspace }}/target/release/test_pipeline

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: ./artifacts
          DEST_DIR: nbari/test_pipeline
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
